### ISSUE TITLE
Template stack will not compile due to linker error

### ISSUE THREAD

**Issue by enadorisan** [FreepMan/data-structs#5]
Branch: Template  stack

Although it is still in development, I want to note that you will not be able to compile the program with template stack used. The problem right now is the separation of definitions of member functions of template class. It will generate linker errors under most of the compilers. I would recommend to create .hpp header with code you have in .cpp and include it at the end of template stack header or just keep the declarations in the header.
![image](https://github.com/FreepMan/data-structs/assets/113302504/bfc5072b-71cd-4b07-a32b-f5a72c30c379)

You can learn more about this issue here: https://stackoverflow.com/questions/115703/storing-c-template-function-definitions-in-a-cpp-file

**Comment by FreepMan** [comment]
This is exactly the problem that appeared! Thank you!

**Comment by enadorisan** [comment]
I want to add several notes: I moved 'template stack' to newly created folder 'src' to actually make the compiler compile that .cpp file with definitions (it will not solve any linker errors tho).

Another note:
'head' in template stack is of type 'Node' but it should be 'Node *'

```cpp
template<typename T>
class Stack{
private:
    struct Node{
        T data;
        Node* prev;
    };
    Node head; // this is where the problem with 'head' is
public:
    Stack() {};
    Stack(T);
    Stack &push(T);
    T pop();
    T top();
    T bot();
    void free();
};
```
